
import { Product } from './types';

export const COLORS = {
  primary: '#EF4444', // Red-500
  secondary: '#1E3A8A', // Blue-900
  accent: '#F59E0B', // Amber-500
};

export const PRODUCTS: Product[] = [
  {
    id: '9',
    name: 'Mini Ventilador Climatizador USB Portátil',
    description: '❄️ Perfeito para o calor! Refresca e umidifica o ar com eficiência. Ideal para ambientes pequenos, como quarto, escritório ou mesa de trabalho. Alimentação via USB – use no notebook, PC ou carregador comum. Compacto, leve e fácil de levar pra qualquer lugar. Produto novo e pronto pra entrega em Cascavel!',
    price: 89.90,
    originalPrice: 149.00,
    image: 'https://images.unsplash.com/photo-1591123120675-6f7f1aae0e5b?q=80&w=800&auto=format&fit=crop',
    category: 'Casa',
    rating: 4.9,
    reviewsCount: 12,
    stock: 25,
    deliveryToday: true,
    isBestSeller: true,
    hasFreeShipping: true,
    tags: ['Calor', 'Promoção', 'Top 1'],
    upsellIds: ['u1']
  },
  {
    id: '1',
    name: 'Smartwatch Ultra Pro Max 2024',
    description: 'Monitoramento de saúde completo, GPS integrado e bateria de 7 dias. O companheiro ideal para sua rotina em Cascavel.',
    price: 249.90,
    originalPrice: 399.00,
    image: 'https://picsum.photos/seed/watch/600/600',
    category: 'Eletrônicos',
    rating: 4.8,
    reviewsCount: 156,
    stock: 15,
    deliveryToday: true,
    isBestSeller: true,
    hasFreeShipping: true,
    tags: ['Promoção', 'Entrega Hoje'],
    upsellIds: ['u1', 'u2']
  },
  {
    id: 'u1',
    name: 'Película de Proteção 3D Nano',
    description: 'Proteção máxima contra riscos e quedas para seu Smartwatch.',
    price: 19.90,
    image: 'https://picsum.photos/seed/film/600/600',
    category: 'Acessórios',
    rating: 4.9,
    reviewsCount: 450,
    stock: 100,
    deliveryToday: true,
    isBestSeller: false,
    tags: ['Essencial']
  },
  {
    id: 'u2',
    name: 'Pulseira Silicone Sport Extra',
    description: 'Várias cores para personalizar seu estilo.',
    price: 35.00,
    image: 'https://picsum.photos/seed/strap/600/600',
    category: 'Acessórios',
    rating: 4.7,
    reviewsCount: 230,
    stock: 45,
    deliveryToday: true,
    isBestSeller: false,
    tags: []
  },
  {
    id: '2',
    name: 'Fone Bluetooth Noise Cancelling',
    description: 'Som imersivo com cancelamento de ruído ativo. Perfeito para quem busca foco e qualidade sonora superior.',
    price: 189.00,
    originalPrice: 250.00,
    image: 'https://picsum.photos/seed/headphones/600/600',
    category: 'Acessórios',
    rating: 4.5,
    reviewsCount: 89,
    stock: 10,
    deliveryToday: false,
    isBestSeller: false,
    tags: ['Novidade'],
    upsellIds: ['u3']
  },
  {
    id: 'u3',
    name: 'Case de Silicone Protetora',
    description: 'Evite danos ao estojo de carga do seu fone.',
    price: 29.90,
    image: 'https://picsum.photos/seed/case/600/600',
    category: 'Acessórios',
    rating: 4.8,
    reviewsCount: 120,
    stock: 60,
    deliveryToday: true,
    isBestSeller: false,
    tags: []
  },
  {
    id: '3',
    name: 'Luminária Inteligente RGB',
    description: 'Controle pelo celular, milhões de cores para transformar seu ambiente em Cascavel. Compatível com Alexa.',
    price: 79.90,
    originalPrice: 120.00,
    image: 'https://picsum.photos/seed/lamp/600/600',
    category: 'Casa',
    rating: 4.7,
    reviewsCount: 42,
    stock: 20,
    deliveryToday: true,
    isBestSeller: true,
    tags: ['Entrega Hoje'],
    upsellIds: ['u4']
  },
  {
    id: 'u4',
    name: 'Lâmpada Reserva Inteligente 9W',
    description: 'Nunca fique no escuro, tenha sempre uma reserva à mão.',
    price: 45.00,
    image: 'https://picsum.photos/seed/bulb/600/600',
    category: 'Acessórios',
    rating: 4.6,
    reviewsCount: 15,
    stock: 10,
    deliveryToday: true,
    isBestSeller: false,
    tags: []
  },
  {
    id: '4',
    name: 'Kit Gamer Teclado + Mouse RGB',
    description: 'Alta precisão e ergonomia para suas partidas. Iluminação personalizável e switches mecânicos.',
    price: 159.00,
    originalPrice: 220.00,
    image: 'https://picsum.photos/seed/gaming/600/600',
    category: 'Informática',
    rating: 4.9,
    reviewsCount: 112,
    stock: 8,
    deliveryToday: true,
    isBestSeller: false,
    tags: ['Mais Vendido'],
    upsellIds: ['u5']
  },
  {
    id: 'u5',
    name: 'Mousepad Gamer Speed XL',
    description: '80x30cm para total liberdade de movimento.',
    price: 49.90,
    image: 'https://picsum.photos/seed/mousepad/600/600',
    category: 'Informática',
    rating: 4.8,
    reviewsCount: 88,
    stock: 15,
    deliveryToday: true,
    isBestSeller: false,
    tags: ['Essencial']
  },
  {
    id: '5',
    name: 'Câmera de Segurança 360 WiFi',
    description: 'Monitore sua casa de onde estiver com imagem HD e visão noturna.',
    price: 199.90,
    image: 'https://picsum.photos/seed/camera/600/600',
    category: 'Eletrônicos',
    rating: 4.6,
    reviewsCount: 34,
    stock: 12,
    deliveryToday: true,
    isBestSeller: false,
    tags: ['Segurança']
  },
  {
    id: '6',
    name: 'Teclado Mecânico Compacto 60%',
    description: 'Switches azuis, iluminação RGB e design minimalista.',
    price: 210.00,
    image: 'https://picsum.photos/seed/keyboard/600/600',
    category: 'Informática',
    rating: 4.7,
    reviewsCount: 56,
    stock: 5,
    deliveryToday: false,
    isBestSeller: false,
    tags: ['Gamer']
  },
  {
    id: '7',
    name: 'Suporte Articulado para Monitor',
    description: 'Melhore sua ergonomia no home office em Cascavel.',
    price: 145.00,
    image: 'https://picsum.photos/seed/monitor/600/600',
    category: 'Informática',
    rating: 4.9,
    reviewsCount: 22,
    stock: 18,
    deliveryToday: true,
    isBestSeller: false,
    tags: ['Escritório']
  },
  {
    id: '8',
    name: 'Lixeira Inteligente com Sensor',
    description: 'Abertura automática e vedação de odores para sua cozinha.',
    price: 129.00,
    image: 'https://picsum.photos/seed/bin/600/600',
    category: 'Casa',
    rating: 4.4,
    reviewsCount: 15,
    stock: 7,
    deliveryToday: true,
    isBestSeller: false,
    tags: ['Smart Home']
  }
];

export const CATEGORIES = ['Todos', 'Eletrônicos', 'Acessórios', 'Casa', 'Informática'];
